version: "3.9"

volumes:
  pgdata:

services:
  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 5432:5432
  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --log-level=error
    volumes:
      - .:/code
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
