version: "3.9"

volumes:
  pgdata:

services:
  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      #- DJANGO_DEBUG=True
    depends_on:
      - db
